export * from './administration.service';
import { AdministrationService } from './administration.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './bloc.service';
import { BlocService } from './bloc.service';
export * from './feedbacks.service';
import { FeedbacksService } from './feedbacks.service';
export * from './line.service';
import { LineService } from './line.service';
export * from './sector.service';
import { SectorService } from './sector.service';
export * from './spraywallProblems.service';
import { SpraywallProblemsService } from './spraywallProblems.service';
export * from './spraywalls.service';
import { SpraywallsService } from './spraywalls.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AdministrationService, AuthService, BlocService, FeedbacksService, LineService, SectorService, SpraywallProblemsService, SpraywallsService, UserService];
