export const FONT_GRADE = {
  one: '1',
  two: '2',
  three: '3',
  fourA: '4a',
  fourB: '4b',
  fourC: '4c',
  fiveA: '5a',
  fiveB: '5b',
  fiveC: '5c',
  sixA: '6a',
  sixAPlus: '6a+',
  sixB: '6b',
  sixBPlus: '6b+',
  sixC: '6c',
  sixCPlus: '6c+',
  sevenA: '7a',
  sevenAPlus: '7a+',
  sevenB: '7b',
  sevenBPlus: '7b+',
  sevenC: '7c',
  sevenCPlus: '7c+',
  eightA: '8a',
  eightAPlus: '8a+',
  eightB: '8b',
  eightBPlus: '8b+',
  eightC: '8c',
  eightCPlus: '8c+',
  nineA: '9a',
  nineAPlus: '9a+',
  nineB: '9b',
  nineBPlus: '9b+',
  nineC: '9c',
} as const;

export type FontGrade = keyof typeof FONT_GRADE;
