nelmio_api_doc:
    documentation:
        info:
            title: Bi-Ba-Boulder
            description: 3D Bouldering Guide
            version: 0.1.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!/doc$) # Accepts routes under / except /doc
