/**
 * Bi-Ba-Boulder
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BlocDto { 
    id: string;
    name: string;
    description: string;
    blocLowRes: string;
    blocMedRes: string;
    blocHighRes: string;
}

