/**
 * Bi-Ba-Boulder
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostSearchProblemsRequest { 
    /**
     * min Font grade
     */
    gradeMin?: number;
    /**
     * max Font grade
     */
    gradeMax?: number;
    /**
     * Problem name
     */
    name?: string;
    /**
     * Creator username or ID
     */
    creator?: string;
    /**
     * asc or desc
     */
    dateOrder?: string;
    /**
     * Page number for pagination
     */
    page?: number;
}

