/**
 * Bi-Ba-Boulder
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostRegisterRequest { 
    /**
     * Email of the user
     */
    email: string;
    /**
     * Password of the user
     */
    password: string;
}

