/**
 * Bi-Ba-Boulder
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PutCreateRequest { 
    /**
     * Name of the spraywall problem
     */
    name: string;
    /**
     * Description of the spraywall problem
     */
    description?: string | null;
    /**
     * PNG image as base64 string (format: data:image/png;base64,<base64-data>)
     */
    image: string;
    /**
     * Font grade of the spraywall problem
     */
    fontGrade: number | null;
}

