/**
 * Bi-Ba-Boulder
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpraywallProblemsDto { 
    id: string;
    name: string;
    image: string;
    description?: string | null;
}

