/**
 * Bi-Ba-Boulder
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id: string;
    email: string;
    roles: Array<any>;
}

