/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicResourceDto } from './publicResourceDto';
import { SpraywallDto } from './spraywallDto';


export interface BoulderGymDto { 
    id?: string;
    name: string;
    description?: string | null;
    importantInfo?: string | null;
    previewImageUri?: string | null;
    images?: Array<PublicResourceDto>;
    spraywalls?: Array<SpraywallDto>;
}

