/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserSectorAccessCommand { 
    userId: string;
    sectorId: string;
    accessSourceType: number;
    validUntil?: string | null;
}

