/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateBlocCommand { 
    name: string;
    sectorId?: string | null;
    description?: string | null;
    coordinates?: string | null;
    blocLowRes?: string | null;
    blocMedRes?: string | null;
    blocHighRes?: string | null;
    previewImageUri?: string | null;
}

