/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LineData } from './lineData';


export interface CreateLineCommand { 
    blocId: string;
    identifier: string;
    name?: string | null;
    description?: string | null;
    fontGrade?: number;
    data: LineData;
}

