/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LineData } from './lineData';
import { LineMetadataDto } from './lineMetadataDto';


export interface LineDto { 
    id: string;
    identifier: string;
    fontGrade?: number;
    description?: string | null;
    name?: string | null;
    data?: LineData;
    version: number;
    metadata: LineMetadataDto;
}

