/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SceneMarking } from './sceneMarking';


export interface LineData { 
    positions?: Array<Array<number>>;
    someMoreStuff?: string | null;
    sceneMarkings?: Array<SceneMarking>;
}

