/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LineDto { 
    id: string;
    identifier: string;
    description?: string | null;
    color?: string | null;
    name?: string | null;
}

