/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicResourceDto } from './publicResourceDto';
import { SectorDto } from './sectorDto';


export interface OutdoorAreaDto { 
    id?: string;
    name: string;
    description?: string | null;
    importantInfo?: string | null;
    images?: Array<PublicResourceDto>;
    sectors?: Array<SectorDto>;
}

