/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SceneMarking { 
    type?: number;
    form?: number;
    position?: Array<number>;
    scale?: Array<number>;
    quaternion?: Array<number>;
}

