/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchProblemsRequest { 
    gradeMin?: number;
    gradeMax?: number;
    name?: string | null;
    creator?: string | null;
    dateOrder?: string | null;
    page?: number | null;
}

