/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateSpraywallProblemCommandFontGrade } from './createSpraywallProblemCommandFontGrade';


export interface SearchProblemsRequest { 
    gradeMin?: CreateSpraywallProblemCommandFontGrade | null;
    gradeMax?: CreateSpraywallProblemCommandFontGrade | null;
    name?: string | null;
    creator?: string | null;
    dateOrder?: string | null;
    page?: CreateSpraywallProblemCommandFontGrade | null;
}

