/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpraywallProblemListDtoTotalCount } from './spraywallProblemListDtoTotalCount';
import { SpraywallProblemDto } from './spraywallProblemDto';


export interface SpraywallProblemListDto { 
    totalCount: SpraywallProblemListDtoTotalCount;
    currentPage: SpraywallProblemListDtoTotalCount;
    problems: Array<SpraywallProblemDto>;
}

