/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpraywallProblemMetadataDto } from './spraywallProblemMetadataDto';


export interface SpraywallProblemDto { 
    id: string;
    name: string;
    image: string;
    fontGrade?: number;
    createdById: string;
    createdByName: string;
    createdDate: string;
    version: number;
    description?: string | null;
    metadata: SpraywallProblemMetadataDto;
}

