/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateBoulderLogCommand { 
    id: string;
    version: number;
    isSent: boolean;
    isProject: boolean;
    rating?: number;
    fontGrade?: number;
}

