/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateOutdoorAreaCommand { 
    sectorIds?: Array<string>;
    isPublic?: boolean | null;
    name: string;
    description?: string | null;
    importantInfo?: string | null;
    previewImageUri?: string | null;
    imageUris?: Array<string>;
    version?: number;
}

