/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UriAliasAdministrationDto { 
    id: string;
    alias: string;
    typeId: number;
    targetId: string;
    targetName: string;
    version: number;
}

