// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thecell.Bibaboulder.Model;

#nullable disable

namespace BiBaBoulder.Migrations
{
    [DbContext(typeof(BiBaBoulderDbContext))]
    [Migration("20260814101427_AddedPreviewImageForBloc")]
    partial class AddedPreviewImageForBloc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OutdoorAreaSector", b =>
                {
                    b.Property<Guid>("OutdoorAreasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectorsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OutdoorAreasId", "SectorsId");

                    b.HasIndex("SectorsId");

                    b.ToTable("OutdoorAreaSector");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Access.UserSectorAccess", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessSourceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "SectorId");

                    b.HasIndex("SectorId");

                    b.ToTable("UserSectorAccesses");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.BoulderLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FontGrade")
                        .HasColumnType("int");

                    b.Property<bool>("IsProject")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("SpraywallProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SpraywallProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("BoulderLogs");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bcc")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cc")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplyTo")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoulderLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAttempt")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSend")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BoulderLogId");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Outdoor.Bloc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlocHighRes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("BlocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlocLowRes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("BlocMedRes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PreviewImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BlocId");

                    b.HasIndex("SectorId");

                    b.ToTable("Blocs");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Outdoor.Line", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FontGrade")
                        .HasColumnType("int");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BlocId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Outdoor.OutdoorArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportantInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PreviewImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OutdoorAreas");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Outdoor.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportantInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PreviewImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Spraywall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PreviewImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Spraywalls");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.SpraywallProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FontGrade")
                        .HasColumnType("int");

                    b.Property<bool>("FreeFeet")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCircuit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWip")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("NoMatch")
                        .HasColumnType("bit");

                    b.Property<Guid>("SpraywallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SpraywallId");

                    b.ToTable("SpraywallProblems");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("OidcSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("VerifyMailSentTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OutdoorAreaSector", b =>
                {
                    b.HasOne("Thecell.Bibaboulder.Model.Model.Outdoor.OutdoorArea", null)
                        .WithMany()
                        .HasForeignKey("OutdoorAreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thecell.Bibaboulder.Model.Model.Outdoor.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Access.UserSectorAccess", b =>
                {
                    b.HasOne("Thecell.Bibaboulder.Model.Model.Outdoor.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thecell.Bibaboulder.Model.Model.User", "User")
                        .WithMany("UserSectorAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.BoulderLog", b =>
                {
                    b.HasOne("Thecell.Bibaboulder.Model.Model.SpraywallProblem", "SpraywallProblem")
                        .WithMany("BoulderLogs")
                        .HasForeignKey("SpraywallProblemId");

                    b.HasOne("Thecell.Bibaboulder.Model.Model.User", "User")
                        .WithMany("BoulderLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpraywallProblem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.LogEntry", b =>
                {
                    b.HasOne("Thecell.Bibaboulder.Model.Model.BoulderLog", "BoulderLog")
                        .WithMany("LogEntries")
                        .HasForeignKey("BoulderLogId");

                    b.Navigation("BoulderLog");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Outdoor.Bloc", b =>
                {
                    b.HasOne("Thecell.Bibaboulder.Model.Model.Outdoor.Bloc", null)
                        .WithMany("AdditionalParts")
                        .HasForeignKey("BlocId");

                    b.HasOne("Thecell.Bibaboulder.Model.Model.Outdoor.Sector", "Sector")
                        .WithMany("Blocs")
                        .HasForeignKey("SectorId");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Outdoor.Line", b =>
                {
                    b.HasOne("Thecell.Bibaboulder.Model.Model.Outdoor.Bloc", "Bloc")
                        .WithMany("BoulderLines")
                        .HasForeignKey("BlocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bloc");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Outdoor.OutdoorArea", b =>
                {
                    b.OwnsMany("Thecell.Bibaboulder.Model.Model.Outdoor.PublicResource", "Media", b1 =>
                        {
                            b1.Property<Guid>("OutdoorAreaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Uri")
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.Property<int>("ResourceType")
                                .HasColumnType("int");

                            b1.HasKey("OutdoorAreaId", "Uri", "ResourceType");

                            b1.ToTable("OutdoorAreaImages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OutdoorAreaId");
                        });

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Outdoor.Sector", b =>
                {
                    b.OwnsMany("Thecell.Bibaboulder.Model.Model.Outdoor.PublicResource", "Media", b1 =>
                        {
                            b1.Property<Guid>("SectorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Uri")
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.Property<int>("ResourceType")
                                .HasColumnType("int");

                            b1.HasKey("SectorId", "Uri", "ResourceType");

                            b1.ToTable("SectorImages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SectorId");
                        });

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.SpraywallProblem", b =>
                {
                    b.HasOne("Thecell.Bibaboulder.Model.Model.User", "Creator")
                        .WithMany("SpraywallProblems")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thecell.Bibaboulder.Model.Model.Spraywall", "Spraywall")
                        .WithMany("SpraywallProblems")
                        .HasForeignKey("SpraywallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Spraywall");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.BoulderLog", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Outdoor.Bloc", b =>
                {
                    b.Navigation("AdditionalParts");

                    b.Navigation("BoulderLines");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Outdoor.Sector", b =>
                {
                    b.Navigation("Blocs");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.Spraywall", b =>
                {
                    b.Navigation("SpraywallProblems");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.SpraywallProblem", b =>
                {
                    b.Navigation("BoulderLogs");
                });

            modelBuilder.Entity("Thecell.Bibaboulder.Model.Model.User", b =>
                {
                    b.Navigation("BoulderLogs");

                    b.Navigation("SpraywallProblems");

                    b.Navigation("UserSectorAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
