export const ICONS = [
  'none',
  'loading',
  'filter-asc',
  'filter-desc',
  'filter',
  'tag-empty',
  'tag-filled',
  'sent-empty',
  'sent-filled',
  'eye-empty',
  'eye-filled',
  'expand-empty',
  'expand-filled',
  'asterisk',
  'projector-empty',
  'projector-filled',
  'paperclip-empty',
  'paperclip-filled',
  'expand-alt-empty',
  'expand-alt-filled',
  'check-square',
  'times-square',
  'square',
  'star-empty',
  'star-filled'
] as const;
export type IconType = (typeof ICONS)[number];
