export * from './administration.service';
import { AdministrationService } from './administration.service';
export * from './administration.serviceInterface';
export * from './bff.service';
import { BffService } from './bff.service';
export * from './bff.serviceInterface';
export * from './blocs.service';
import { BlocsService } from './blocs.service';
export * from './blocs.serviceInterface';
export * from './feedbacks.service';
import { FeedbacksService } from './feedbacks.service';
export * from './feedbacks.serviceInterface';
export * from './lines.service';
import { LinesService } from './lines.service';
export * from './lines.serviceInterface';
export * from './sectors.service';
import { SectorsService } from './sectors.service';
export * from './sectors.serviceInterface';
export * from './spraywallProblems.service';
import { SpraywallProblemsService } from './spraywallProblems.service';
export * from './spraywallProblems.serviceInterface';
export * from './spraywalls.service';
import { SpraywallsService } from './spraywalls.service';
export * from './spraywalls.serviceInterface';
export * from './test.service';
import { TestService } from './test.service';
export * from './test.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export const APIS = [AdministrationService, BffService, BlocsService, FeedbacksService, LinesService, SectorsService, SpraywallProblemsService, SpraywallsService, TestService, UsersService];
