export * from './administration.service';
import { AdministrationService } from './administration.service';
export * from './administration.serviceInterface';
export * from './bff.service';
import { BffService } from './bff.service';
export * from './bff.serviceInterface';
export * from './blocs.service';
import { BlocsService } from './blocs.service';
export * from './blocs.serviceInterface';
export * from './boulderGym.service';
import { BoulderGymService } from './boulderGym.service';
export * from './boulderGym.serviceInterface';
export * from './boulderLogs.service';
import { BoulderLogsService } from './boulderLogs.service';
export * from './boulderLogs.serviceInterface';
export * from './devAuth.service';
import { DevAuthService } from './devAuth.service';
export * from './devAuth.serviceInterface';
export * from './feedbacks.service';
import { FeedbacksService } from './feedbacks.service';
export * from './feedbacks.serviceInterface';
export * from './lines.service';
import { LinesService } from './lines.service';
export * from './lines.serviceInterface';
export * from './medias.service';
import { MediasService } from './medias.service';
export * from './medias.serviceInterface';
export * from './outdoorAreas.service';
import { OutdoorAreasService } from './outdoorAreas.service';
export * from './outdoorAreas.serviceInterface';
export * from './sectors.service';
import { SectorsService } from './sectors.service';
export * from './sectors.serviceInterface';
export * from './spraywallProblems.service';
import { SpraywallProblemsService } from './spraywallProblems.service';
export * from './spraywallProblems.serviceInterface';
export * from './spraywalls.service';
import { SpraywallsService } from './spraywalls.service';
export * from './spraywalls.serviceInterface';
export * from './test.service';
import { TestService } from './test.service';
export * from './test.serviceInterface';
export * from './userSectorAccesses.service';
import { UserSectorAccessesService } from './userSectorAccesses.service';
export * from './userSectorAccesses.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export const APIS = [AdministrationService, BffService, BlocsService, BoulderGymService, BoulderLogsService, DevAuthService, FeedbacksService, LinesService, MediasService, OutdoorAreasService, SectorsService, SpraywallProblemsService, SpraywallsService, TestService, UserSectorAccessesService, UsersService];
