/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface BffServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns the current user\&#39;s claims as JSON.  The Angular app calls this to check if a session is active and to retrieve user info.  Returns 401 if the user is not authenticated.
     * 
     */
    getUser(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Initiates the OIDC Authorization Code + PKCE flow by redirecting to the Identity Provider.  The Angular app should navigate to this URL (not call it via AJAX).
     * 
     * @param returnUrl Path to redirect back to after successful login. Defaults to \&quot;/\&quot;.
     */
    login(returnUrl?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Signs out of the local cookie session and the OIDC Identity Provider.
     * 
     */
    logout(extraHttpRequestParams?: any): Observable<{}>;

}
