/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BlocDto } from '../model/models';
import { CreateBlocCommand } from '../model/models';
import { DeleteBlocCommand } from '../model/models';
import { UpdateBlocCommand } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BlocsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createBlocCommand 
     */
    createBloc(createBlocCommand: CreateBlocCommand, extraHttpRequestParams?: any): Observable<BlocDto>;

    /**
     * 
     * 
     * @param id 
     * @param deleteBlocCommand 
     */
    deleteBloc(id: string, deleteBlocCommand: DeleteBlocCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    getBloc(id: string, extraHttpRequestParams?: any): Observable<BlocDto>;

    /**
     * 
     * 
     * @param sectorId 
     */
    getBlocsBySectorId(sectorId: string, extraHttpRequestParams?: any): Observable<Array<BlocDto>>;

    /**
     * 
     * 
     * @param id 
     * @param updateBlocCommand 
     */
    updateBloc(id: string, updateBlocCommand: UpdateBlocCommand, extraHttpRequestParams?: any): Observable<BlocDto>;

}
