/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BoulderLogDto } from '../model/models';
import { CreateBoulderLogCommand } from '../model/models';
import { DeleteBoulderLogCommand } from '../model/models';
import { UpdateBoulderLogCommand } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BoulderLogsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createBoulderLogCommand 
     */
    createBoulderLog(createBoulderLogCommand: CreateBoulderLogCommand, extraHttpRequestParams?: any): Observable<BoulderLogDto>;

    /**
     * 
     * 
     * @param id 
     * @param deleteBoulderLogCommand 
     */
    deleteBoulderLog(id: string, deleteBoulderLogCommand: DeleteBoulderLogCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    getBoulderLog(id: string, extraHttpRequestParams?: any): Observable<BoulderLogDto>;

    /**
     * 
     * 
     */
    getBoulderLogs(extraHttpRequestParams?: any): Observable<Array<BoulderLogDto>>;

    /**
     * 
     * 
     * @param id 
     * @param updateBoulderLogCommand 
     */
    updateBoulderLog(id: string, updateBoulderLogCommand: UpdateBoulderLogCommand, extraHttpRequestParams?: any): Observable<BoulderLogDto>;

}
