/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddSpraywallToBoulderGymCommand } from '../model/models';
import { BoulderGymDto } from '../model/models';
import { CreateBoulderGymCommand } from '../model/models';
import { DeleteBoulderGymCommand } from '../model/models';
import { UpdateBoulderGymCommand } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BoulderGymServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     * @param addSpraywallToBoulderGymCommand 
     */
    addSpraywallToBoulderGym(id: string, addSpraywallToBoulderGymCommand: AddSpraywallToBoulderGymCommand, extraHttpRequestParams?: any): Observable<BoulderGymDto>;

    /**
     * 
     * 
     * @param createBoulderGymCommand 
     */
    createBoulderGym(createBoulderGymCommand: CreateBoulderGymCommand, extraHttpRequestParams?: any): Observable<BoulderGymDto>;

    /**
     * 
     * 
     * @param id 
     * @param deleteBoulderGymCommand 
     */
    deleteBoulderGym(id: string, deleteBoulderGymCommand: DeleteBoulderGymCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    getBoulderGym(id: string, extraHttpRequestParams?: any): Observable<BoulderGymDto>;

    /**
     * 
     * 
     */
    getBoulderGyms(extraHttpRequestParams?: any): Observable<Array<BoulderGymDto>>;

    /**
     * 
     * 
     * @param id 
     * @param spraywallId 
     */
    removeSpraywallFromBoulderGym(id: string, spraywallId: string, extraHttpRequestParams?: any): Observable<BoulderGymDto>;

    /**
     * 
     * 
     * @param id 
     * @param updateBoulderGymCommand 
     */
    updateBoulderGym(id: string, updateBoulderGymCommand: UpdateBoulderGymCommand, extraHttpRequestParams?: any): Observable<BoulderGymDto>;

}
