/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BoulderGymDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BoulderGymServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    getBoulderGym(id: string, extraHttpRequestParams?: any): Observable<BoulderGymDto>;

    /**
     * 
     * 
     */
    getBoulderGyms(extraHttpRequestParams?: any): Observable<Array<BoulderGymDto>>;

}
