/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface DevAuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Mock login endpoint for development. Creates/uses a test user and signs in with cookies.
     * 
     * @param email Email of the test user. Defaults to \&quot;dev@test.local\&quot;.
     */
    devLogin(email?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Clear the development session.
     * 
     */
    devLogout(extraHttpRequestParams?: any): Observable<{}>;

}
