/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SendFeedbackCommand } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FeedbacksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param sendFeedbackCommand 
     */
    sendFeedback(sendFeedbackCommand: SendFeedbackCommand, extraHttpRequestParams?: any): Observable<{}>;

}
