/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LineDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LinesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param blocId 
     */
    getLinesByBlocId(blocId: string, extraHttpRequestParams?: any): Observable<Array<LineDto>>;

}
