/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateLineCommand } from '../model/models';
import { DeleteLineCommand } from '../model/models';
import { LineDto } from '../model/models';
import { UpdateLineCommand } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LinesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param blocId 
     * @param createLineCommand 
     */
    createLineForBloc(blocId: string, createLineCommand: CreateLineCommand, extraHttpRequestParams?: any): Observable<LineDto>;

    /**
     * 
     * 
     * @param id 
     * @param deleteLineCommand 
     */
    deleteLine(id: string, deleteLineCommand: DeleteLineCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param blocId 
     */
    getLinesByBlocId(blocId: string, extraHttpRequestParams?: any): Observable<Array<LineDto>>;

    /**
     * 
     * 
     * @param id 
     * @param updateLineCommand 
     */
    updateLine(id: string, updateLineCommand: UpdateLineCommand, extraHttpRequestParams?: any): Observable<LineDto>;

}
