/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UriAliasDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MediasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param alias 
     * @param type 
     */
    getUriAlias(alias: string, type: number, extraHttpRequestParams?: any): Observable<UriAliasDto>;

}
