/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUriAliasCommand } from '../model/models';
import { DeleteUriAliasCommand } from '../model/models';
import { UpdateUriAliasCommand } from '../model/models';
import { UriAliasAdministrationDto } from '../model/models';
import { UriAliasDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MediasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createUriAliasCommand 
     */
    createUriAlias(createUriAliasCommand: CreateUriAliasCommand, extraHttpRequestParams?: any): Observable<UriAliasAdministrationDto>;

    /**
     * 
     * 
     * @param id 
     * @param deleteUriAliasCommand 
     */
    deleteUriAlias(id: string, deleteUriAliasCommand: DeleteUriAliasCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param alias 
     * @param type 
     */
    getUriAlias(alias: string, type: number, extraHttpRequestParams?: any): Observable<UriAliasDto>;

    /**
     * 
     * 
     * @param id 
     */
    getUriAliasById(id: string, extraHttpRequestParams?: any): Observable<UriAliasAdministrationDto>;

    /**
     * 
     * 
     */
    getUriAliases(extraHttpRequestParams?: any): Observable<Array<UriAliasAdministrationDto>>;

    /**
     * 
     * 
     * @param id 
     * @param updateUriAliasCommand 
     */
    updateUriAlias(id: string, updateUriAliasCommand: UpdateUriAliasCommand, extraHttpRequestParams?: any): Observable<UriAliasAdministrationDto>;

}
