/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateSectorCommand } from '../model/models';
import { SectorDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SectorsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createSectorCommand 
     */
    createSector(createSectorCommand: CreateSectorCommand, extraHttpRequestParams?: any): Observable<SectorDto>;

    /**
     * 
     * 
     * @param id 
     */
    getSector(id: string, extraHttpRequestParams?: any): Observable<SectorDto>;

    /**
     * 
     * 
     */
    getSectors(extraHttpRequestParams?: any): Observable<Array<SectorDto>>;

}
