/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateSpraywallProblemCommand } from '../model/models';
import { SearchProblemsRequest } from '../model/models';
import { SpraywallDto } from '../model/models';
import { SpraywallProblemDto } from '../model/models';
import { SpraywallProblemListDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SpraywallsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     * @param createSpraywallProblemCommand 
     */
    createSpraywallProblem(id: string, createSpraywallProblemCommand: CreateSpraywallProblemCommand, extraHttpRequestParams?: any): Observable<SpraywallProblemDto>;

    /**
     * 
     * 
     */
    getSpraywalls(extraHttpRequestParams?: any): Observable<Array<SpraywallDto>>;

    /**
     * 
     * 
     * @param id 
     * @param searchProblemsRequest 
     */
    searchSpraywallProblems(id: string, searchProblemsRequest?: SearchProblemsRequest, extraHttpRequestParams?: any): Observable<SpraywallProblemListDto>;

}
