/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SpraywallProblemDto } from '../model/models';
import { UpdateSpraywallProblemCommand } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SpraywallProblemsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    deleteProblem(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    getProblem(id: string, extraHttpRequestParams?: any): Observable<SpraywallProblemDto>;

    /**
     * 
     * 
     * @param id 
     * @param updateSpraywallProblemCommand 
     */
    updateProblem(id: string, updateSpraywallProblemCommand: UpdateSpraywallProblemCommand, extraHttpRequestParams?: any): Observable<{}>;

}
