/**
 * BiBaBoulder API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserSectorAccessCommand } from '../model/models';
import { DeleteUserSectorAccessCommand } from '../model/models';
import { UpdateUserSectorAccessCommand } from '../model/models';
import { UserSectorAccessDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserSectorAccessesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createUserSectorAccessCommand 
     */
    createUserSectorAccess(createUserSectorAccessCommand: CreateUserSectorAccessCommand, extraHttpRequestParams?: any): Observable<UserSectorAccessDto>;

    /**
     * 
     * 
     * @param userId 
     * @param sectorId 
     * @param deleteUserSectorAccessCommand 
     */
    deleteUserSectorAccess(userId: string, sectorId: string, deleteUserSectorAccessCommand: DeleteUserSectorAccessCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param userId 
     * @param sectorId 
     */
    getUserSectorAccess(userId: string, sectorId: string, extraHttpRequestParams?: any): Observable<UserSectorAccessDto>;

    /**
     * 
     * 
     */
    getUserSectorAccesses(extraHttpRequestParams?: any): Observable<Array<UserSectorAccessDto>>;

    /**
     * 
     * 
     * @param userId 
     * @param sectorId 
     * @param updateUserSectorAccessCommand 
     */
    updateUserSectorAccess(userId: string, sectorId: string, updateUserSectorAccessCommand: UpdateUserSectorAccessCommand, extraHttpRequestParams?: any): Observable<UserSectorAccessDto>;

}
