namespace Thecell.Bibaboulder.Model.Enums;

public enum FontGrade : int
{
    OneMinus = 0,
    One = 1,
    OnePlus = 2,
    TwoMinus = 3,
    Two = 4,
    TwoPlus = 5,
    ThreeMinus = 6,
    Three = 7,
    ThreePlus = 8,
    FourMinus = 9,
    Four = 10,
    FourPlus = 11,
    FiveMinus = 12,
    Five = 13,
    FivePlus = 14,
    SixAMinus = 15,
    SixA = 16,
    SixAPlus = 17,
    SixBMinus = 18,
    SixB = 19,
    SixBPlus = 20,
    SixCMinus = 21,
    SixC = 22,
    SixCPlus = 23,
    SevenAMinus = 24,
    SevenA = 25,
    SevenAPlus = 26,
    SevenBMinus = 27,
    SevenB = 28,
    SevenBPlus = 29,
    SevenCMinus = 30,
    SevenC = 31,
    SevenCPlus = 32,
    EightAMinus = 33,
    EightA = 34,
    EightAPlus = 35,
    EightBMinus = 36,
    EightB = 37,
    EightBPlus = 38,
    EightCMinus = 39,
    EightC = 40,
    EightCPlus = 41,
    NineAMinus = 42,
    NineA = 43,
    NineAPlus = 44,
    NineBMinus = 45,
    NineB = 46,
    NineBPlus = 47,
    NineCMinus = 48,
    NineC = 49,
    NineCPlus = 50
}
